const a = [
  { name: 'Wedding', icon: 'wedding.png' },
  { name: 'Fotografi', icon: 'photography.png', selected: true },
  { name: 'Kue', icon: 'cake.png' },
  { name: 'Catering', icon: 'catering.png' },
  { name: 'Dekorasi', icon: 'decoration.png' },
  { name: 'Sound', icon: 'sound.png' },
  { name: 'Venue', icon: 'venue.png' },
  { name: 'Undangan', icon: 'invitation.png' },
  { name: 'Pakaian', icon: 'dress.png' },
  { name: 'Upacara Adat', icon: 'ceremony.png' },
  { name: 'Gedung', icon: 'hall.png' },
  { name: 'Perhiasan', icon: 'jewelry.png' },
  { name: 'Makeup', icon: 'makeup.png' },
  { name: 'MC', icon: 'mc.png' },
  { name: 'Hantaran', icon: 'parcel.png' },
  { name: 'Photo Booth', icon: 'photobooth.png' },
  { name: 'Souvenir', icon: 'souvenir.png' },
  { name: 'Hiburan', icon: 'music.png' },
];
export default a
