const kategori = [
  { value: 'wedding', label: 'Wedding', icon: 'wedding.png' },
  { value: 'fotografi', label: 'Fotografi', icon: 'photography.png', selected: true },
  { value: 'kue', label: 'Kue', icon: 'cake.png' },
  { value: 'catering', label: 'Catering', icon: 'catering.png' },
  { value: 'dekorasi', label: 'Dekorasi', icon: 'decoration.png' },
  { value: 'sound', label: 'Sound', icon: 'sound.png' },
  { value: 'venue', label: 'Venue', icon: 'venue.png' },
  { value: 'undangan', label: 'Undangan', icon: 'invitation.png' },
  { value: 'pakaian', label: 'Pakaian', icon: 'dress.png' },
  { value: 'upacara_adat', label: 'Upacara Adat', icon: 'ceremony.png' },
  { value: 'gedung', label: 'Gedung', icon: 'hall.png' },
  { value: 'perhiasan', label: 'Perhiasan', icon: 'jewelry.png' },
  { value: 'makeup', label: 'Makeup', icon: 'makeup.png' },
  { value: 'mc', label: 'MC', icon: 'mc.png' },
  { value: 'hantaran', label: 'Hantaran', icon: 'parcel.png' },
  { value: 'photo booth', label: 'Photo Booth', icon: 'photobooth.png' },
  { value: 'souvenir', label: 'Souvenir', icon: 'souvenir.png' },
  { value: 'hiburan', label: 'Hiburan', icon: 'music.png' },
];
export default kategori
